# .github/workflows/ci.yml

name: Multi-Service Integration Test

on: [push, pull_request]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    
    services:
      redis:
        image: redis:latest
        ports:
          # This line is the key: It maps the container's port 6379
          # to port 6379 on the runner's localhost interface.
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: pip install -r requirements.txt

      - name: Run Integration Tests
        run: pytest
        env:
          # --- THIS IS THE FIX ---
          # We will force the connection to go through localhost (127.0.0.1),
          # which is guaranteed to work because of the port mapping above.
          # We are no longer relying on the 'redis' hostname.
          REDIS_HOST: 127.0.0.1